version: "2"
services:
  qgisserver:
    restart: always
    image: gisquick/qgis-server
    volumes:
      - ./_data/publish:/publish/
    ports:
      - "9090:90"

  django:
    restart: always
    image: gisquick/django-dev
    links:
      - qgisserver
    volumes:
      - ./_data/media:/var/www/gisquick/media/
      - ./_data/data:/var/www/gisquick/data/
      - ./_data/publish:/publish/
      - ../server/webgis:/var/www/gisquick/webgis/
    environment:
      - GUNICORN_ERRORLOG=-
      - GUNICORN_ACCESSLOG=-
      - DJANGO_GISQUICK_UPLOAD_MAX_SIZE='100M'
    ports:
      - "8000:8000"

  nodejs:
    image: gisquick/js-dev:alpine
    volumes:
      - ../clients/src:/gisquick/clients/src
      - ../clients/web:/gisquick/clients/web
      - ./_data/publish:/publish
    ports:
      - "8100:8100"
      - "35729:35729"
